---
title: "Lab 4 Data Analysis"
author: "Lab 4 Data Analysis Committee"
date: "2/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read.csv("./data.csv")
```

```{r}
force_areas <- function(positive_force, negative_force) {
  i <- 1
  positive_sum <- 0
  negative_sum <- 0
  
  positive_median <- median(positive_force)
  negative_median <- median(negative_force)
  
  for (i in 1:251) {
    positive_sum <- positive_sum + positive_force[i] - positive_median;
    negative_sum <- negative_sum + negative_force[i] - negative_median;
    
  }
  
  positive_total_force <- positive_sum * 0.01
  negative_total_force <- negative_sum * 0.01
  
  c(positive_total_force, negative_total_force)
}
```

```{r}
test_trial <- function(start, end, experiment) {
  results <- data.frame()
  
  for (i in start:end) {
    x_name <- paste("Data.Set.", i, "..Force.G..N.", sep="")
    y_name <- paste("Data.Set.", i, "..Force.Y..N.", sep="")
    
    m <- force_areas(data[, x_name], data[, y_name])
    results <- rbind(results, data.frame(force=m[1], car="Yellow Car", experiment))
    results <- rbind(results, data.frame(force=m[2], car="Blue Car", experiment))
  }
  
  results
}

```

```{r}
calc_err <- function(data) {
  yellow.car.force = data[data$car == "Yellow Car", "force"]
  blue.car.force = data[data$car == "Blue Car", "force"]
  
  yellow.car.abs.err <- (max(yellow.car.force) - min(yellow.car.force)) / 2
  blue.car.abs.err <- (max(blue.car.force) - min(blue.car.force)) / 2
  
  yellow.car.rel.err <- yellow.car.abs.err / mean(yellow.car.force)
  blue.car.rel.err <- blue.car.abs.err / mean(blue.car.force)
  
  data.frame(yellow.car.abs.err, yellow.car.rel.err, blue.car.abs.err, blue.car.rel.err)
}
```

### Experiment 1

Moving heavy car (yellow) colliding with moving light car (blue)

```{r}
exp.1.data <- test_trial(1,5, "Experiment 1")
calc_err(exp.1.data)
```

```{r}
exp.1.data
```

### Experiment 2

Moving heavy car (yellow) colliding with stationary light car (blue)

```{r}
exp.2.data <- test_trial(6,10, "Experiment 2")
calc_err(exp.2.data)
```

```{r}
exp.2.data
```

### Experiment 3

Moving light car (blue) colliding with stationary heavy car (yellow)

```{r}
exp.3.data <- test_trial(11,15, "Experiment 3")
calc_err(exp.3.data)
```

```{r}
exp.3.data
```

### Experiment 4

Moving light car (yellow) colliding with moving light car (blue)

```{r}
exp.4.data <- test_trial(16,20, "Experiment 4")
calc_err(exp.4.data)
```

```{r}
exp.4.data
```

## Graph

```{r}
library(ggplot2)
results <- rbind(exp.1.data, exp.2.data, exp.3.data, exp.4.data)

ggplot(results, aes(x=factor(experiment), y=force, fill=factor(car))) +
  geom_boxplot() +
  labs(x="Experiment", y = "Total Force Measured (N)") +
  guides(fill=guide_legend("Car"))
```